# Generated by Django 5.2.15 on 2026-07-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_annotationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField(help_text='Normalized relative coordinates list schema: [[x1, y1], [x2, y2], ...]')),
                ('label', models.CharField(blank=True, help_text='Optional semantic class label identifier.', max_length=100)),
                ('image', models.ForeignKey(help_text='The parent background digital image surface.', on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='api.annotationimage')),
            ],
        ),
    ]
